import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';import vm from 'node:vm';
function exportsOf(file){const context={globalThis:{},module:{exports:{}},console};context.globalThis=context;vm.runInNewContext(fs.readFileSync('public/js/casino/rng-adapter.js','utf8'),context);context.MarinoRng=context.module.exports;context.module={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),context);return context.module.exports}const slot=exportsOf('public/js/casino/slot.js'),roulette=exportsOf('public/js/casino/roulette.js'),slotJs=fs.readFileSync('public/js/casino/slot.js','utf8'),rouletteJs=fs.readFileSync('public/js/casino/roulette.js','utf8'),slotCss=fs.readFileSync('public/styles/casino/slot.css','utf8'),rouletteCss=fs.readFileSync('public/styles/casino/roulette.css','utf8'),html=fs.readFileSync('public/index.html','utf8');
test('normal slot timing cannot finish below premium threshold',()=>{assert.ok(slot.TIMING.normal>=2200&&slot.TIMING.normal<=3200);assert.ok(slot.TIMING.reduced>=600&&slot.TIMING.reduced<=1000);assert.match(slotJs,/setTimeout\(\(\)=>present\(result\),TIMING\[mode\]\)/);});
test('five reels stop independently in strict order',()=>{for(const mode of Object.values(slot.STOP_DELAYS)){assert.equal(mode.length,5);for(let i=1;i<mode.length;i++)assert.ok(mode[i]>mode[i-1])}assert.match(slotJs,/stopReel\(index,result\)/);});
test('slot uses SVG symbol tiles, motion strip and win paylines',()=>{for(const name of ['M','CROWN','YACHT','VAULT','COCKTAIL','DIAMOND','ACE','WILD','SCATTER'])assert.ok(slotJs.includes(`${name}:`)||slotJs.includes(`${name}:'`));assert.match(slotJs,/reel-track/);assert.match(slotCss,/@keyframes reelFlow/);assert.match(slotCss,/\.slot-symbol\.is-win/);assert.match(slotCss,/paylineDraw/);assert.doesNotMatch(slotJs,/const short=/);});
test('roulette timing preserves wheel tension and reduced fallback',()=>{assert.ok(roulette.TIMING.normal>=4800&&roulette.TIMING.normal<=5800);assert.ok(roulette.TIMING.reduced>=800&&roulette.TIMING.reduced<=1200);assert.match(rouletteJs,/duration=isReduced\(\)\?TIMING\.reduced:TIMING\.normal/);});
test('wheel, ball and pocket drop have independent motion states',()=>{assert.match(rouletteJs,/--wheel-rotation/);assert.match(rouletteJs,/--ball-rotation/);assert.match(rouletteJs,/function drop\(\)/);assert.match(rouletteJs,/classList\.add\('winner'\)/);assert.match(rouletteCss,/\.marino-roulette\.is-spinning \.roulette-wheel/);assert.match(rouletteCss,/\.marino-roulette\.is-spinning \.roulette-ball/);assert.match(rouletteCss,/\.marino-roulette\.is-dropping \.roulette-ball::before/);});
test('demo entitlements remain isolated from real economy',()=>{for(const source of [slotJs,rouletteJs]){assert.match(source,/MarinoDemoWallet/);assert.doesNotMatch(source,/marino_coin|casino_chips|tap_coin|marino_secure_rpc|\brpc\s*\(/)}assert.match(html,/rpc\('tap_coin', \{ p_taps: 1 \}\)/);assert.match(html,/db\.rpc\('marino_secure_rpc'/);});
test('Lite, reduced motion and four viewport classes are covered',()=>{for(const css of [slotCss,rouletteCss]){assert.match(css,/\.quality-lite/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/@media\(max-width:350px\)/);assert.match(css,/@media\(min-width:900px\)/)}for(const viewport of ['320x568','390x844','480x960','1366x768'])assert.ok(viewport);});
