import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';import vm from 'node:vm';
function load(){const context={globalThis:{},module:{exports:{}},console};context.globalThis=context;vm.runInNewContext(fs.readFileSync('public/js/casino/rng-adapter.js','utf8'),context);context.MarinoRng=context.module.exports;context.module={exports:{}};vm.runInNewContext(fs.readFileSync('public/js/casino/slot.js','utf8'),context);return{rng:context.MarinoRng,slot:context.module.exports};}const {slot}=load();
test('same seed returns the same 5x3 result',()=>{assert.deepEqual(slot.createEngine('marino-42').spin(),slot.createEngine('marino-42').spin());});
test('reel result and evaluation remain consistent',()=>{const result=slot.createEngine('audit').spin();assert.equal(result.grid.length,5);assert.ok(result.grid.every(reel=>reel.length===3));assert.deepEqual(result.evaluation,slot.evaluate(result.grid));});
test('wild substitutes from the left and scatter is counted globally',()=>{assert.equal(slot.evaluateLine(['WILD','M','M','ACE','M']).count,3);const grid=Array.from({length:5},()=>['SCATTER','ACE','M']);assert.equal(slot.evaluate(grid).scatters,5);});
test('twenty paylines and demo paytable catalogue are explicit',()=>{const data=JSON.parse(fs.readFileSync('public/data/casino/slot-paytable.json'));assert.equal(slot.LINES.length,20);assert.equal(data.paylines,20);assert.match(data.authority,/Demo presentation/);});
test('state machine prevents concurrent spin entry',()=>{const js=fs.readFileSync('public/js/casino/slot.js','utf8');assert.match(js,/!\[STATES\.IDLE,STATES\.BETTING,STATES\.FREE_SPIN\]\.includes\(status\)/);for(const state of ['IDLE','BETTING','SPINNING','STOPPING','EVALUATING','PRESENTING_WIN','FREE_SPIN','ERROR'])assert.equal(slot.STATES[state],state);});
test('free spin consumes only memory demo entitlement and real coin is absent',()=>{const js=fs.readFileSync('public/js/casino/slot.js','utf8');assert.match(js,/MarinoDemoWallet\?\.consume\?\.\('spin'\)/);assert.doesNotMatch(js,/tap_coin|marino_secure_rpc|\brpc\s*\(|marino_coin|casino_chips/);});
test('slot UI has reduced-motion and Lite fallbacks',()=>{const css=fs.readFileSync('public/styles/casino/slot.css','utf8');assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/\.quality-lite/);});
