import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';
const html=fs.readFileSync('public/index.html','utf8'),shell=fs.readFileSync('public/js/casino/game-shell.js','utf8'),lobby=fs.readFileSync('public/js/casino/casino-lobby.js','utf8'),wallet=fs.readFileSync('public/js/casino/demo-wallet.js','utf8'),css=fs.readFileSync('public/styles/casino/game-shell.css','utf8');
test('professional lobby exposes server-backed flagship games',()=>{for(const label of ['Marino Fortune Slots','Marino European Roulette','Blackjack Lounge','VIP Baccarat'])assert.match(lobby,new RegExp(label));assert.match(lobby,/Sonuc ve bakiye sunucu onaylidir/);assert.match(lobby,/GERCEK BAKIYE/);});
test('legacy mini game code remains but lobby does not render it',()=>{assert.match(html,/function openMini/);assert.match(lobby,/listStore/);assert.doesNotMatch(lobby,/openMini\(/);});
test('shared shell supports close Escape BackButton rules history and session',()=>{for(const pattern of [/event\.key === 'Escape'/,/BackButton/,/data-shell-action="rules"/,/data-shell-action="history"/,/casinoShellSession/,/requestFullscreen/])assert.match(shell,pattern);});
test('shell hides navigation locks scroll and covers compact viewport',()=>{assert.match(css,/casino-game-open \.nav-bar/);assert.match(css,/casino-scroll-lock/);assert.match(css,/@media\(max-width:350px\)/);assert.match(css,/safe-area-inset-top/);});
test('active rounds require exit confirmation and background input is blocked',()=>{assert.match(shell,/state\.game\?\.isActive/);assert.match(shell,/window\.confirm/);assert.match(shell,/event\.stopPropagation\(\)/);});
test('demo wallet is memory only and real mode cannot consume rights',()=>{assert.match(wallet,/memory-only-demo/);assert.match(wallet,/if\(!preview\(\)/);assert.doesNotMatch(wallet,/fetch|XMLHttpRequest|localStorage|sessionStorage|\brpc\s*\(/);});
test('casino core modules are linked and protected contracts remain present',()=>{for(const file of ['demo-wallet.js','rng-adapter.js','game-shell.js','casino-lobby.js'])assert.match(html,new RegExp(file.replace('.','\\.')));assert.match(html,/rpc\('tap_coin', \{ p_taps: batchSize \}\)/);assert.match(html,/db\.rpc\('marino_secure_rpc'/);});
