import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';import vm from 'node:vm';
function load(){const context={globalThis:{},module:{exports:{}},console};context.globalThis=context;vm.runInNewContext(fs.readFileSync('public/js/casino/rng-adapter.js','utf8'),context);context.MarinoRng=context.module.exports;context.module={exports:{}};vm.runInNewContext(fs.readFileSync('public/js/casino/roulette.js','utf8'),context);return context.module.exports;}const roulette=load();
test('European wheel contains 0 through 36 exactly once and one zero',()=>{assert.equal(roulette.WHEEL.length,37);assert.equal(new Set(roulette.WHEEL).size,37);assert.equal(roulette.WHEEL.filter(n=>n===0).length,1);assert.deepEqual([...roulette.WHEEL].sort((a,b)=>a-b),Array.from({length:37},(_,i)=>i));});
test('official red black green mapping is stable',()=>{assert.equal(roulette.color(0),'green');for(const n of [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36])assert.equal(roulette.color(n),'red');assert.equal(roulette.color(2),'black');});
test('inside and outside demo payouts evaluate correctly',()=>{const bets=[{type:'straight',numbers:[17],amount:10},{type:'red',numbers:[],amount:10},{type:'dozen',numbers:[],index:2,amount:10}];const result=roulette.evaluate(bets,17);assert.equal(result.payout,390);assert.equal(result.wins.length,2);assert.equal(roulette.PAYOUT.straight,35);assert.equal(roulette.PAYOUT.split,17);assert.equal(roulette.PAYOUT.street,11);assert.equal(roulette.PAYOUT.corner,8);assert.equal(roulette.PAYOUT.sixline,5);assert.equal(roulette.PAYOUT.dozen,2);assert.equal(roulette.PAYOUT.column,2);});
test('visual wheel result and deterministic RNG share the same index',()=>{const a=roulette.createEngine('wheel-seed').spin(),b=roulette.createEngine('wheel-seed').spin();assert.deepEqual(a,b);assert.equal(roulette.WHEEL[a.index],a.number);});
test('two concurrent spins and empty bets are blocked',()=>{const js=fs.readFileSync('public/js/casino/roulette.js','utf8');assert.match(js,/phase === STATES\.SPINNING/);assert.match(js,/phase === STATES\.SETTLING/);assert.match(js,/phase === STATES\.PRESENTING_RESULT/);assert.match(js,/if \(!bets\.length\) return message/);assert.match(js,/if \(!canBet\(\)\) return false/);});
test('production roulette uses server economy bridge and keeps unsupported bets closed',()=>{const js=fs.readFileSync('public/js/casino/roulette.js','utf8');assert.match(js,/MarinoEconomyBridge/);assert.match(js,/await bridge\.playRoulette\(serverPayload\(\)\)/);assert.match(js,/henuz sunucu kontratinda yok/);assert.doesNotMatch(js,/MarinoDemoWallet\?\.credit|MarinoDemoWallet\?\.debit|tap_coin|marino_secure_rpc|\brpc\s*\(|marino_coin|casino_chips/);});
test('roulette data declares presentation authority and UI fallbacks',()=>{const data=JSON.parse(fs.readFileSync('public/data/casino/roulette-layout.json'));assert.match(data.authority,/Demo presentation/);const css=fs.readFileSync('public/styles/casino/roulette.css','utf8');assert.match(css,/@media\(max-width:350px\)/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/\.quality-lite/);});
