import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

const html=fs.readFileSync('public/index.html','utf8');
const daily=fs.readFileSync('public/js/daily-rewards.js','utf8');
const audio=fs.readFileSync('public/js/audio-manager.js','utf8');
const css=fs.readFileSync('public/styles/daily-rewards.css','utf8');
const manifest=JSON.parse(fs.readFileSync('public/assets/asset-manifest.json','utf8'));

test('daily reward is a closable sheet with a real SVG close control',()=>{assert.match(html,/id="fsDaily" class="sheet-overlay daily-reward-overlay"/);assert.match(html,/id="closeDaily"[\s\S]*?<svg viewBox="0 0 24 24"/);assert.match(daily,/querySelector\('#closeDaily'\)\?\.addEventListener\('click',close\)/);});
test('Escape, backdrop and Telegram BackButton close to Tasks',()=>{assert.match(daily,/event\.key==='Escape'/);assert.match(daily,/event\.target===overlay\(\)/);assert.match(daily,/BackButton/);assert.match(daily,/back\.onClick\(close\)/);assert.match(daily,/back\.offClick\?\.\(close\)/);assert.match(daily,/window\.showTab\?\.\('tasks'\)/);});
test('daily grid contains exactly seven compact reward definitions',()=>{assert.equal([...daily.matchAll(/day:\d/g)].length,7);assert.match(css,/max-width:64px/);assert.match(css,/max-height:64px/);assert.match(css,/aspect-ratio:1/);assert.match(css,/object-fit:contain/);assert.match(css,/flex-shrink:0/);});
test('daily cards do not render the raw coin PNG or an eighth day',()=>{const block=html.match(/<!-- DAILY REWARD SHEET -->([\s\S]*?)<!-- MINI GAME/)?.[1]||'';assert.doesNotMatch(block,/marino-coin\.png|<img/i);assert.doesNotMatch(daily,/day:8|i\s*<=\s*8/);});
test('success effects occur only after a successful claim result',()=>{const claim=html.indexOf('async function claimDaily()');const rpc=html.indexOf("rpc('marino_claim_daily_login'",claim);const success=html.indexOf('MarinoDailyRewards?.claimSuccess?.',rpc);const failure=html.indexOf('MarinoDailyRewards?.claimFailure?.',success);assert.ok(rpc>claim&&success>rpc&&failure>success);assert.doesNotMatch(html.slice(failure,failure+120),/claimSuccess/);assert.match(daily,/notificationOccurred\?\.\('success'\)/);assert.match(daily,/MarinoAudio\?\.play\?\.\('daily_reward'\)/);});
test('local preview claim is memory-only and precedes the RPC branch',()=>{const claim=html.indexOf('async function claimDaily()');const preview=html.indexOf('if (isLocalPreview)',claim);const rpc=html.indexOf("rpc('marino_claim_daily_login'",claim);assert.ok(preview>claim&&preview<rpc);assert.match(html.slice(preview,rpc),/daily_login\.current_streak/);});
test('direct daily preview helper remains localhost testmode gated',()=>{assert.match(daily,/MarinoLocalPreview\?\.detect/);assert.match(daily,/get\('daily'\)==='1'/);});
test('Free Spin and Free Bet carry explicit virtual no-cash language',()=>{assert.match(daily,/Sanal hak, nakit değeri yoktur/);assert.match(html,/Sanal Free Spin ve Free Bet nakit değeri taşımaz/);assert.match(daily,/freeSpin:/);assert.match(daily,/freeBet:/);});
test('audio manager fails safely to procedural fallback without 404 loops',()=>{assert.match(audio,/if\(!definition\.available\|\|state\.failed\.has\(id\)\)return null/);assert.ok(audio.indexOf('if(!definition.available')<audio.indexOf('fetch(definition.file'));assert.match(audio,/return procedural\(definition\)/);assert.match(audio,/state\.missingReported/);});
test('disabled SFX cannot create or play an AudioContext',()=>{assert.ok(audio.indexOf('if(!state.unlocked||!sfxEnabled())return false')<audio.indexOf('const ctx=context()'));assert.match(audio,/MAX_VOICES:6/);assert.match(audio,/definition\.rateLimit/);});
test('asset manifest records provenance, licensing, size and fallback',()=>{assert.ok(manifest.assets.length>=20);for(const asset of manifest.assets){for(const field of ['id','file','type','usage','source','license','sizeBytes','fallback'])assert.ok(Object.hasOwn(asset,field),`${asset.id} missing ${field}`)}assert.equal(manifest.policy.externalDownloads,false);});
test('responsive daily sheet covers target viewport classes',()=>{assert.match(css,/@media\(max-width:339px\)/);assert.match(css,/@media\(min-width:390px\)/);assert.match(css,/@media\(max-height:600px\)/);assert.match(css,/overflow-y:auto/);assert.match(css,/position:sticky/);});
test('protected contracts and static IDs remain intact',()=>{assert.match(html,/function authenticateTelegram\(/);assert.match(html,/db\.rpc\('marino_secure_rpc'/);assert.match(html,/rpc\('tap_coin', \{ p_taps: 1 \}\)/);assert.match(html,/function processState\(d\)/);const markup=html.replace(/<script(?:\s[^>]*)?>[\s\S]*?<\/script>/gi,'');const ids=[...markup.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length);});
