import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';import vm from 'node:vm';
const js=fs.readFileSync('public/js/casino/roulette.js','utf8'),css=fs.readFileSync('public/styles/casino/roulette.css','utf8'),html=fs.readFileSync('public/index.html','utf8');
function load(){const context={globalThis:{},module:{exports:{}},console};context.globalThis=context;vm.runInNewContext(fs.readFileSync('public/js/casino/rng-adapter.js','utf8'),context);context.MarinoRng=context.module.exports;context.module={exports:{}};vm.runInNewContext(js,context);return context.module.exports}const roulette=load();
test('all 37 wheel labels have outer-ring geometry and readable layers',()=>{const markup=roulette.WHEEL.map(roulette.pocketMarkup).join('');assert.equal([...markup.matchAll(/data-pocket="/g)].length,37);assert.equal([...markup.matchAll(/data-pocket="0"/g)].length,1);assert.match(css,/top:0;width:var\(--pocket-width\);height:50%/);assert.match(css,/transform-origin:50% 100%/);assert.match(css,/font-size:8px/);assert.match(css,/\.roulette-wheel-label\{z-index:3\}/);assert.match(css,/\.roulette-wheel>\.roulette-pocket\{[^}]*z-index:6/);});
test('every roulette control template is an explicit non-submit button',()=>{const source=js.match(/function markup\(\)[\s\S]*?function descriptorFrom/)[0];const buttons=[...source.matchAll(/<button\b([^>]*)>/g)];assert.ok(buttons.length>=15);for(const button of buttons)assert.match(button[1],/type="button"/);assert.match(roulette.numberMarkup(12),/type="button"/);});
test('button guard prevents default bubbling and avoids forced viewport scroll',()=>{assert.match(js,/event\.preventDefault\(\)/);assert.match(js,/event\.stopPropagation\(\)/);assert.match(js,/focus\(\{ preventScroll: true \}\)/);assert.doesNotMatch(js,/scrollIntoView|window\.scrollTo/);});
test('chip markers cannot resize grid or cover the number label',()=>{assert.match(css,/\.roulette-grid\{contain:layout\}/);assert.match(css,/\.chip-marker\{position:absolute!important;pointer-events:none;contain:strict/);assert.match(css,/overflow-anchor:none/);assert.match(css,/scroll-behavior:auto/);assert.match(css,/button\{touch-action:manipulation\}/);assert.match(css,/button>span:first-child\{[^}]*transform:translate/);});
test('result pocket and table still share the exact server or RNG number',()=>{assert.match(js,/data-pocket="\$\{result\.number\}"/);assert.match(js,/covers\(candidate,\s*result\.number\)/);assert.match(js,/result\.number/);assert.match(js,/WHEEL\[index\]/);});
test('protected contracts and static IDs remain intact',()=>{assert.match(html,/rpc\('tap_coin', \{ p_taps: batchSize \}\)/);assert.match(html,/db\.rpc\('marino_secure_rpc'/);assert.doesNotMatch(js,/marino_coin|casino_chips|tap_coin|marino_secure_rpc|\brpc\s*\(/);const markup=html.replace(/<script(?:\s[^>]*)?>[\s\S]*?<\/script>/gi,'');const ids=[...markup.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);assert.equal(ids.length,new Set(ids).size);});
